# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Neverland' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Neverland
  pod 'DropDown'
  pod 'SCLAlertView'
  pod 'CommonCryptoModule', '~> 1.0.1'

  target 'NeverlandTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NeverlandUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
